In [1]:
import pandas as pd
import numpy as np

In [2]:
trainFile = '../data/train.csv'
testFile = '../data/test.csv'

In [3]:
train = pd.read_csv(trainFile)
test = pd.read_csv(testFile)

In [4]:
train.head()

,qid,question_text,target
0,00002165364db923c7e6,How did Quebec nationalists see their province...,0
1,000032939017120e6e44,"Do you have an adopted dog, how would you enco...",0
2,0000412ca6e4628ce2cf,Why does velocity affect time? Does velocity a...,0
3,000042bf85aa498cd78e,How did Otto von Guericke used the Magdeburg h...,0
4,0000455dfa3e01eae3af,Can I convert montra helicon D to a mountain b...,0

In [5]:
train[['question_text']].head()

                                       question_text
0  How did Quebec nationalists see their province...
1  Do you have an adopted dog, how would you enco...
2  Why does velocity affect time? Does velocity a...
3  How did Otto von Guericke used the Magdeburg h...
4  Can I convert montra helicon D to a mountain b...

In [6]:
test.head()

                    qid                                      question_text
0  0000163e3ea7c7a74cd7  Why do so many women become so rude and arroga...
1  00002bd4fb5d505b9161  When should I apply for RV college of engineer...
2  00007756b4a147d2b0b3  What is it really like to be a nurse practitio...
3  000086e4b7e1c7146103                             Who are entrepreneurs?
4  0000c4c3fbe8785a3090   Is education really making good people nowadays?

In [7]:
train['wordCount'] = train['question_text'].apply(lambda x: len(x.split()))

In [8]:
train['characterCount'] = train['question_text'].apply(lambda x: len(x))

In [9]:
train.head()

,qid,question_text,target,wordCount,characterCount
0,00002165364db923c7e6,How did Quebec nationalists see their province...,0,13,72
1,000032939017120e6e44,"Do you have an adopted dog, how would you enco...",0,16,81
2,0000412ca6e4628ce2cf,Why does velocity affect time? Does velocity a...,0,10,67
3,000042bf85aa498cd78e,How did Otto von Guericke used the Magdeburg h...,0,9,57
4,0000455dfa3e01eae3af,Can I convert montra helicon D to a mountain b...,0,15,77

In [10]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
train['stopwords'] = train['question_text'].apply(lambda x: len([x for x in x.split() if x in stop]))
train.head()

,qid,question_text,target,wordCount,characterCount,stopwords
0,00002165364db923c7e6,How did Quebec nationalists see their province...,0,13,72,6
1,000032939017120e6e44,"Do you have an adopted dog, how would you enco...",0,16,81,8
2,0000412ca6e4628ce2cf,Why does velocity affect time? Does velocity a...,0,10,67,1
3,000042bf85aa498cd78e,How did Otto von Guericke used the Magdeburg h...,0,9,57,2
4,0000455dfa3e01eae3af,Can I convert montra helicon D to a mountain b...,0,15,77,5

In [11]:
avgWords = train['wordCount'].mean()
avgChars = train['characterCount'].mean()
avgWordsSincere = train.loc[train['target'] == 0]['wordCount'].mean()
avgWordsInsincere = train.loc[train['target'] == 1]['wordCount'].mean()
avgCharsSincere = train.loc[train['target'] == 0]['characterCount'].mean()
avgCharsInsincere = train.loc[train['target'] == 1]['characterCount'].mean()
print(avgWords, avgChars, avgWordsSincere, avgWordsInsincere, \
      avgCharsSincere, avgWordsInsincere)

12.803609463740754 70.67883551459971 12.50853333681544 17.277812151961392 68.87275812201301 17.277812151961392

In [19]:
#min words 1 - 24 such sentences, all insincere
#max words 134
#train.sort_values(['wordCount']).head()

,qid,question_text,target,wordCount,characterCount,stopwords
402155,4ecb7f4ae1327f0af618,Feminism:,1,1,10,0
480439,5e156d295da9a4413769,Nepal:,1,1,7,0
299304,3a9ae962f1094242e36f,If,1,1,3,0
420816,527aac2ce6f12f789fe5,"""",1,1,1,0
644979,7e51cb67f97bdbc2f2b3,Wicca:,1,1,7,0

In [20]:
#min chars 1
#max chars 1017
#train.sort_values(['characterCount']).head()

,qid,question_text,target,wordCount,characterCount,stopwords
420816,527aac2ce6f12f789fe5,"""",1,1,1,0
995257,c309469a202434b5f1d2,W,1,1,1,0
299304,3a9ae962f1094242e36f,If,1,1,3,0
792939,9b5f4ae97ad53ac06ba6,Do,1,1,3,0
78445,0f5a41d6752d5d667895,Is,1,1,3,0